---
name: Reset State
on:
  schedule:
    - cron: "15 1 * * 1-5"
jobs:
 reset:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: sync
    
    - name: Run app
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run python reset.py
      env:
        client_id: ${{ secrets.client_id }}
        client_secret: ${{ secrets.client_secret }}
        userid: ${{ secrets.userid }}
        topic: ${{ secrets.topic }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
