---
name: Alert temp
on:
  schedule:
    - cron: "*/15 11-20 * * 1-5"
jobs:
 alert-temp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: sync
    
    - name: Run app
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run python temperatura.py
      env:
        client_id: ${{ secrets.client_id }}
        client_secret: ${{ secrets.client_secret }}
        userid: ${{ secrets.userid }}
        topic: ${{ secrets.topic }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
